### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [shomarov/fullstackopen-2019-project#3]
# Katselmointi

Terve @shomarov! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän ja kirjauduin sisään
- Lisäsin uuden reseptin
- Selailin reseptien luonnoksia ja julkaisin lisäämäni reseptin
- Muokkasin reseptiäni
- Tsekkasin profiilitietoni
- Muokkasin profiilitietojani
- Kirjauduin ulos

### Kokemus

- Käyttöliittymä on hieman askeettinen, mutta täysin käyttökelpoinen. Hyvää työtä!
- Lomakkeissa on pääosin hyvät virheilmoitukset
- Reseptin lisäämisen jälkeen käyttäjälle voisi tulla jokin ilmoitus, että reseptin lisääminen onnistui. Tällä hetkellä reseptin lisäämisen jälkeen lomake vain tyhjenee
- Geneerin "React App"-titlen ja faviconin voisi muuttaa kuvaavammaksi

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Hyvää fragmenttien käyttöä frontendin GraphQL-kyselyissä
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL-apin resolverit ja tyyppimääritelmät voisi eritellä sen sijaan, että ne olisivat samassa tiedossa, esim. tähän tapaan: https://github.com/Kaltsoon/rate-repository-api/tree/master/src/graphql
- Hyvää data loaderien käyttöä GraphQL-apissa 🏆

## Kokonaisuus

- Sovelluksessa on kaikki sen käyttötarkoitukseen tarvittava toiminallisuus, eikä sen käytettävyydessä ole suurempia ongelmia, vaikka käyttöliittymmä onkin tyylillisesti hieman karu.
- Koodi on suurimmilta hyvin organisoitua, vaikkakin GraphQL-apin toteutusta voisi vähän vielä pilkkoa. Myös koodin sisäinen laadun puolesta homma on aika hyvin kunnossa

**Comment by shomarov** [comment]
Kiitos!
